# Generated by Django 5.1.3 on 2025-03-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single Room'), ('Double', 'Double Room'), ('Suite', 'Suite'), ('King', 'King Room'), ('Queen', 'Queen Room'), ('Deluxe', 'Deluxe Room'), ('Penthouse', 'Penthouse')], default='Single', max_length=20),
        ),
    ]
