# Generated by Django 5.1.3 on 2024-11-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0003_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='rooms/room7.jpg', upload_to='rooms/'),
        ),
    ]
